version:3
services:
    postgress:
         image: postgress:latest
         environment:
            - POSTGRES_PASSWORD="postgres_password"
            - POSTGRES_USER="postgres"
            - POSTGRES_DB="simple_blog_api"
    api:
        depends_on:
           - postgress
        image: sushma04/simple_blog_api
        build: .
        ports:
           - "3000:3000"
        environment:
           - POSTGRES_HOST=postgres
           - POSTGRES_PORT=5432
           - POSTGRES_PASSWORD=postgres_password
           - POSTGRES_USER=postgres
           - POSTGRES_DB=simple_blog_api


      
