# Base Image
FROM node:16-alpine

# Switch Working Dir to '/usr/app'
WORKDIR /usr/app

# Copy over the package.json into
# the container
COPY package.json .

# Install the deps
RUN npm install

# Copy the rest of the files over
COPY . .

# run the App
CMD ["npm", "run" , "start"]