api version: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: simple-blog-api
        image: sushma04/simple-blog-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: POSTGRES_HOST
            value: postgres-cluster-ip-service
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: pgpassord
          - name: POSTGRES_USERNAME
            value: postgres
          - name: POSTGRES_DB
            value: simple_blog_api
                
